apiVersion: apps/v1
kind: Deployment
metadata:
  name: bye-deployment
spec:
  replicas: 2  # Number of pod replicas you want
  selector:
    matchLabels:
      app: bye
  template:
    metadata:
      labels:
        app: bye
    spec:
      containers:
      - name: bye
        image: 025670723498.dkr.ecr.us-east-1.amazonaws.com/hanna-demo/bye:0.4
        ports:
        - containerPort: 80